export const quoteArray = [
  "Uncontrollable laughter",
  "Pop culture tangent",
  "Singing along to music",
  "This wouldn’t work on ladder",
  "This is the current meta",
  "Great connection",
  "Box art army",
  "Tasteless can’t remember unit/upgrade name",
  "Rogue, Trap, Innovation, TY, and Stats are on military service (must say all 5)",
  "Talks about how happy they are that Prince qualified",
  "Artosis references Zest as one of the best protoss",
  "“The Chintoss”",
  "On-camera tastosis depiction fan art",
  "Real life dig at tasteless",
  "“Will Serral ever compete in a GSL?”",
  "Special and Scarlett shown on camera in the crowd",
  "Referencing any match before 2015",
  "Artosis talks about how Flash is best broodwar player ever and it's not close",
  "First G5L prediction",
  "“Serious mindgames”",
  "Tasteless explains how minerals and gas work",
  "Simultaneous “OOOoooOo”",
  "Microsoft acquisition is mentioned",
  "Making fun of other games that arent starcraft",
  "Mentions Stormgate",
];
